import type { Metadata } from "next";
import { Locale, routing } from "@/i18n/routing";
import { ReactNode } from "react";
import BaseLayout from '../components/BaseLayout';
import { notFound } from 'next/navigation';
import { setRequestLocale } from "next-intl/server";

export const metadata: Metadata = {
  title: "AeroStar Aviation",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

type Props = {
  children: ReactNode;
  params: {locale: Locale};
};


export default async function LocaleLayout({ children, params: { locale } }: Props) {
 const validLocale = routing.locales.includes(locale as Locale) ? locale : routing.defaultLocale;

  if (!validLocale) {
    notFound();
  }
  // Enable static rendering
  setRequestLocale(validLocale);
  return <BaseLayout locale={validLocale}>{children}</BaseLayout>;
}
